[libraries]
hasicorp-cdktf = "com.hashicorp:cdktf:0.14.0"
hasicorp-provider-docker = "com.hashicorp:cdktf-provider-docker:3.0.12"
software-constructs = "software.constructs:constructs:10.1.127"

[bundles]
cdktf-docker = ["hasicorp-cdktf", "hasicorp-provider-docker", "software-constructs"]
