[libraries]
hasicorp-cdktf = "com.hashicorp:cdktf:0.14.1"
hasicorp-provider-docker = "com.hashicorp:cdktf-provider-docker:4.0.0"
software-constructs = "software.constructs:constructs:10.1.127"

[bundles]
cdktf-docker = ["hasicorp-cdktf", "hasicorp-provider-docker", "software-constructs"]
