[libraries]
hasicorp-cdktf = "com.hashicorp:cdktf:0.12.0"
hasicorp-provider-docker = "com.hashicorp:cdktf-provider-docker:2.0.14"
software-constructs = "software.constructs:constructs:10.1.69"

[bundles]
cdktf-docker = ["hasicorp-cdktf", "hasicorp-provider-docker", "software-constructs"]